name: Publish to docker registry

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Build env
        run: |
          echo "PKG_VERSION=$(cat docker/judger-env/VERSION)" >> $GITHUB_ENV
          echo "PKG_FULL_VERSION=$(cat docker/judger-env/VERSION)-full" >> $GITHUB_ENV
      - uses: mr-smithers-excellent/docker-build-push@v2
        name: Build judger service image
        with:
          image: ryanlee2014/cupoj-judger
          tag: ${{ env.PKG_VERSION }}
          registry: docker.io
          dockerfile: ./docker/judger/base/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v2
        name: Update judger service image
        with:
          image: ryanlee2014/cupoj-judger
          tag: latest
          registry: docker.io
          dockerfile: ./docker/judger/base/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v2
        name: Update judger service image with full env
        with:
          image: ryanlee2014/cupoj-judger
          tag: ${{ env.PKG_FULL_VERSION }}
          registry: docker.io
          dockerfile: ./docker/judger/full/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
